//action Type
export const GET_BRICOLEURS = "GET_BRICOLEURS";
export const ADD_BRICOLEUR = "ADD_BRICOLEUR";
export const GET_BRICOLEURS_BY_VILLE_BY_SERVICE =
  "GET_BRICOLEURS_BY_VILLE_BY_SERVICE";
export const ADD_CLIENT = "ADD_CLIENT";
export const GET_CLIENTS = "GET_CLIENTS";
export const ADD_MISSION = "ADD_MISSION";
export const GET_MISSIONS = "GET_MISSIONS";
export const GET_MISSIONS_BY_VILLES_BY_SERVICE =
  "GET_MISSIONS_BY_VILLES_BY_SERVICE";
